-- Create with postgre
CREATE TABLE USER_TBL
(
    ID       UUID PRIMARY KEY,
    USERNAME VARCHAR(20)  NOT NULL UNIQUE,
    EMAIL    VARCHAR(35)  NOT NULL UNIQUE,
    PASSWORD VARCHAR(120) NOT NULL,
    BIRTHDAY DATE,
    FULLNAME VARCHAR(40)  NOT NULL
);

